project:
  type: website
  output-dir: docs

website:
  title: "pm566 Final"
  navbar:
    left:
      - href: index.qmd
        text: Midterm Project
      - href: about.qmd  
        text: Download the Report & References

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


